#plot multivariate BF against univariate BF for simulations generated by simset
all.vs.pca.compplot=function(sim,...){
t=sim$t.01
nrep = length(t)
lbfav = rep(0,nrep)
lbfuni = rep(0,nrep)
for(j in 1:nrep){lbfav[j]=t[[j]]$lbfall;
                lbfuni[j] = log10(mean(10^sim$pca[[j]]$lbfuni));}
xmax = max(c(lbfav,lbfuni))
xmin = min(c(lbfav,lbfuni))
if(xmax<12){xmax=12}
if(xmin>-1){xmin=-1}
plot(lbfuni,lbfav,xlim=c(xmin,xmax),ylim=c(xmin,xmax),xlab="log10(pca-based BF)",ylab="log10(BFall)",...)
abline(a=0,b=1)
abline(v=4,h=4,lty=2)
}


#plot multivariate BF against univariate BF for simulations generated by simset
mv.vs.uni.compplot=function(sim,...){
t=sim$t.04
nrep = length(t)
lbfav = rep(0,nrep)
lbfuni = rep(0,nrep)
for(j in 1:nrep){lbfav[j]=t[[j]]$lbfav;
                lbfuni[j] = log10(mean(10^t[[j]]$lbfuni));}
xmax = max(c(lbfav,lbfuni))
xmin = min(c(lbfav,lbfuni))
if(xmax<12){xmax=12}
if(xmin>-1){xmin=-1}
plot(lbfuni,lbfav,xlim=c(xmin,xmax),ylim=c(xmin,xmax),xlab="log10(mean univariate BF)",ylab="log10(multivarate BF)",...)
abline(a=0,b=1)
abline(v=4,h=4,lty=2)
}

#plot multivariate BF against MANOVA for simulations generated by simset
all.vs.man.compplot=function(sim,...){
t=sim$t.04
nrep = length(t)
lbfall = rep(0,nrep)
lbfuni = rep(0,nrep)
for(j in 1:nrep){lbfall[j]=t[[j]]$lbfall;
                lbfuni[j] = -log10(sim$m[[j]]);}
xmax = max(c(lbfall,lbfuni))
xmin = min(c(lbfall,lbfuni))
if(xmax<12){xmax=12}
if(xmin>-1){xmin=-1}
plot(lbfuni,lbfall,xlim=c(xmin,xmax),ylim=c(xmin,xmax),xlab="-log10(MANOVA p value)",ylab="log10(BFall)",...)
abline(a=0,b=1)
abline(v=4,h=4,lty=2)
}

#plot multivariate BF against univariate BF for simulations generated by simset
all.vs.uni.compplot=function(sim,...){
t=sim$t.04
nrep = length(t)
lbfall = rep(0,nrep)
lbfuni = rep(0,nrep)
for(j in 1:nrep){lbfall[j]=t[[j]]$lbfall;
                lbfuni[j] = log10(mean(10^t[[j]]$lbfuni));}
xmax = max(c(lbfall,lbfuni))
xmin = min(c(lbfall,lbfuni))
if(xmax<12){xmax=12}
if(xmin>-1){xmin=-1}
plot(lbfuni,lbfall,xlim=c(xmin,xmax),ylim=c(xmin,xmax),xlab="log10(mean univariate BF)",ylab="log10(BFall)",...)
abline(a=0,b=1)
abline(v=4,h=4,lty=2)
}
